### ISSUE TITLE
Table: column divider is not visible

### ISSUE THREAD

**Issue by tishoyanchev** [Infineon/infineon-design-system-stencil#1568]
### Detailed description of how to reproduce the problem

The basic and advanced table components used to have a visible column divider. Now it's not visible anymore, but hovering over with the mouse indicates that the divider is still there. 

### Upload a screenshot

<img width="1345" alt="Bildschirmfoto 2024-11-06 um 09 34 23" src="https://github.com/user-attachments/assets/0a2db562-2065-4855-ab6d-d21796558ac4">

### Expected behavior

Divider should be visible

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Added a right border to the ag-header-cell and ag-cell classes to create visible column dividers in the basic table component.

I also created pull request: https://github.com/Infineon/infineon-design-system-stencil/pull/1570


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
