### ISSUE TITLE
basic and advanced table - set column width or style

### ISSUE THREAD

**Issue by ralfongit** [Infineon/infineon-design-system-stencil#1620]
### Detailed description of what you want to happen

 It should be possible to set the width of each column in a table like this:
 {
    "headerName": "Price",
    "field": "price",
    "width": "10%"
  },
and / or 
  {
    "headerName": "Price",
    "field": "price",
    "width": "100px"
  },

or even use "style": "some css" to set more than only width

### Why do you need this feature?

I want to show data with longer texts and in other column only number

### Do you have a deadline?

No

**Comment by tishoyanchev** [comment]
Your [issue](https://github.com/orgs/Infineon/projects/4?pane=issue&itemId=89659580&issue=Infineon%7Cinfineon-design-system-stencil%7C1620) has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!
@ralfongit 
Hi Ralf, we have approved the request, but it is uncertain whether this is possible or not due to the ag-grid library limitations. We will investigate, and if possible, we will implement it. If not, we will inform you and then close the issue.

**Comment by tishoyanchev** [comment]
Not needed anymore as the options are already possible
