### ISSUE TITLE
single-select: Does not truncate longer text in option

### ISSUE THREAD

**Issue by ralfongit** [Infineon/infineon-design-system-stencil#1621]
### Detailed description of how to reproduce the problem

If you have a longer text as option of the select, it does not get truncated (with ellipsis) but completely shown with line-break.

### Upload a screenshot

![image](https://github.com/user-attachments/assets/a369faab-43a3-4aa4-b1bd-05581a84ce05)

![image](https://github.com/user-attachments/assets/bbee9e66-0e2b-4f52-b0df-89c119177a9f)

### Expected behavior

Long text should be truncated with ellipsis when text is longer than dropdown width

**Comment by tishoyanchev** [comment]
Your `[issue](https://github.com/orgs/Infineon/projects/4?pane=issue&itemId=89660180&issue=Infineon%7Cinfineon-design-system-stencil%7C1621)` has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!
@ralfongit 
I edited the title because the issue only occurs in single-select.
