### ISSUE TITLE
How to use DS with Next.js? 

### ISSUE THREAD

**Issue by ghost** [Infineon/infineon-design-system-stencil#891]
**Context**

Hey Team, 
My name is Dmytro and I am starting development of new project using Next.js and I'd love you use design system as library of reusable React components.

**Question/Issue**:

I follow ReadMe section and when I put 
```
import { defineCustomElements } from '@infineon/infineon-design-system-react';
//...

defineCustomElements(window)
```
my app (freshly bootstrapped) crushes with following error
```
Uncaught Error: Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
```
which kinda make sense but I'm wandering then how to properly make this `defineCustomElements(window)` definition?

Will DS work with Next.js anyway?

**Comment by tishoyanchev** [comment]
@dmytro-infineon 
Hello! 
Interesting question. Next.js is predominately a client-based framework that allows for server integration, so in theory at least you should be able to install our package and use our components, but if you are getting this error, then perhaps it's not that straightforward. I am going to need to do some testing in order to familiarize myself with it. At the moment, this is not a high priority, and we would have to prioritize more urgent issues. I or my colleague will reach out to you for more information when one of us have the time to take on this issue. Sorry for the inconvenience, and thank you for your patience and feedback.
